# Generated by Django 6.0.4 on 2026-05-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Товар')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Ціна')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опобліковано')),
            ],
            options={
                'verbose_name': 'Оголошення',
                'verbose_name_plural': 'Оголошення',
                'ordering': ['-published'],
            },
        ),
    ]
