# Generated by Django 6.0.4 on 2026-05-02 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_rubric_bd_rubric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bd',
            name='rubric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='samples.rubric', verbose_name='Рубрика'),
        ),
    ]
