# Generated by Django 6.0.4 on 2026-05-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_alter_bd_rubric'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Ім’я')),
                ('last_name', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('middle_name', models.CharField(max_length=50, verbose_name='По батькові')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('region', models.CharField(max_length=100, verbose_name='Область')),
                ('district', models.CharField(max_length=100, verbose_name='Район')),
                ('city', models.CharField(max_length=100, verbose_name='Населений пункт')),
                ('post_service', models.CharField(choices=[('NP', 'Нова Пошта'), ('UP', 'Укрпошта')], default='NP', max_length=2, verbose_name='Пошта')),
                ('post_office', models.CharField(max_length=10, verbose_name='Номер відділення')),
                ('post_address', models.CharField(max_length=255, verbose_name='Вулиця відділення')),
                ('items', models.TextField(verbose_name='Товари')),
                ('total_price', models.FloatField(verbose_name='Загальна сума')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата замовлення')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
            },
        ),
    ]
