# Generated by Django 6.0.4 on 2026-05-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0004_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='post_office',
            field=models.CharField(max_length=10, verbose_name='№ відділення'),
        ),
    ]
