# Generated by Django 6.0.4 on 2026-05-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0005_alter_order_post_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='bd',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фото товару'),
        ),
    ]
