# Generated by Django 6.0.4 on 2026-05-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0006_bd_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bd',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Додаткове фото'),
        ),
        migrations.AlterField(
            model_name='bd',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Головне фото'),
        ),
        migrations.AlterField(
            model_name='bd',
            name='published',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубліковано'),
        ),
    ]
