# Generated by Django 6.0.4 on 2026-05-10 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0007_bd_image_2_alter_bd_image_alter_bd_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rubric',
            options={},
        ),
        migrations.RemoveField(
            model_name='bd',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='district',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='post_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='post_office',
        ),
        migrations.AlterField(
            model_name='bd',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='bd',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='bd',
            name='rubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='samples.rubric', verbose_name='Рубрика'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='order',
            name='post_service',
            field=models.CharField(max_length=50, verbose_name='Служба доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='region',
            field=models.CharField(max_length=50, verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума'),
        ),
    ]
