# Generated by Django 6.0.4 on 2026-05-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0008_alter_rubric_options_remove_bd_image_2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.RemoveField(
            model_name='order',
            name='post_service',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_service',
            field=models.CharField(choices=[('NP', 'Нова Пошта'), ('UP', 'Укрпошта')], default='NP', max_length=2, verbose_name='Служба доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='department',
            field=models.CharField(default=1, max_length=100, verbose_name='Номер відділення'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.TextField(blank=True, verbose_name='Товари'),
        ),
        migrations.AddField(
            model_name='order',
            name='middle_name',
            field=models.CharField(default='', max_length=50, verbose_name='По батькові'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Вулиця'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='order',
            name='region',
            field=models.CharField(max_length=100, verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сума'),
        ),
    ]
