# Generated by Django 6.0.4 on 2026-05-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0009_alter_order_options_remove_order_post_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dilivery_type',
            field=models.CharField(choices=[('branch', 'відділення'), ('poshtomat', 'поштомат'), ('courier', "ку'єром")], default='branch', max_length=10, verbose_name='Спосіб доставки'),
        ),
    ]
