# Generated by Django 6.0.4 on 2026-05-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0010_order_dilivery_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='dilivery_type',
            new_name='delivery_type',
        ),
        migrations.AddField(
            model_name='bd',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='В наявності'),
        ),
    ]
