# Generated by Django 6.0.4 on 2026-05-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0011_rename_dilivery_type_order_delivery_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bd',
            name='stock',
            field=models.PositiveIntegerField(default=1, verbose_name='Кількість на складі'),
        ),
    ]
