# Generated by Django 6.0.4 on 2026-05-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0012_bd_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Кількість'),
        ),
    ]
