# Generated by Django 6.0.4 on 2026-05-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0013_order_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Замовлення', 'verbose_name_plural': 'Замовлення'},
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', '🆕 Нове замовлення'), ('request', '📦 Запит постачальнику'), ('wait', '⏳ Очікує оплати'), ('sent', '🚚 Відправлено'), ('done', '✅ Завершено'), ('cancel', '❌ Скасовано')], default='new', max_length=20, verbose_name='Статус замовлення'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('branch', 'відділення'), ('poshtomat', 'поштомат'), ('courier', "кур'єром")], default='branch', max_length=10, verbose_name='Спосіб доставки'),
        ),
    ]
