# Generated by Django 6.0.4 on 2026-05-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0014_alter_order_options_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bd',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стара ціна'),
        ),
    ]
